# Generated by Django 5.2.4 on 2025-07-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addinvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='付款日期')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='實收金額')),
                ('is_deducted', models.BooleanField(default=False, verbose_name='是否已扣款轉帳')),
                ('processed', models.BooleanField(default=False, verbose_name='已處理')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='addinvoice.invoice', verbose_name='關聯單')),
            ],
        ),
    ]
