# Generated by Django 5.2.4 on 2025-07-31 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='應付日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_date',
            field=models.DateField(blank=True, null=True, verbose_name='實際付款日期'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='實收金額'),
        ),
    ]
