# Generated by Django 5.2.4 on 2025-07-31 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='單名稱')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每月應收金額')),
                ('deduction_recipient', models.CharField(blank=True, max_length=100, null=True, verbose_name='轉帳對象')),
                ('deduction_periods', models.IntegerField(default=0, verbose_name='扣款期數')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
            ],
        ),
    ]
